name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
            distribution: 'temurin'
            java-version: '17'

      - name: Install system build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip autoconf libtool pkg-config zlib1g-dev \
            libncurses-dev libffi-dev libssl-dev build-essential \
            ccache cmake libtool

      - name: Install Buildozer and Cython
        run: |
          pip install --upgrade pip
          pip install buildozer cython virtualenv

      - name: Pre-clone and patch python-for-android
        run: |
          mkdir -p app/.buildozer/android/platform
          git clone -b develop https://github.com/kivy/python-for-android.git app/.buildozer/android/platform/python-for-android
          sed -i 's/"lib\/clang\/\*\/lib\/linux"/"lib*\/clang\/\*\/lib\/linux"/g' app/.buildozer/android/platform/python-for-android/pythonforandroid/recipes/libthorvg/__init__.py

      - name: Build Android APK with Buildozer
        working-directory: ./app
        run: |
          buildozer android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: alertx-debug-apk
          path: app/bin/*.apk
